apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: ag04/jhpetclinic
      context: ../jhipster-petclinic
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
